## Question1

In [1]:
import numpy as np

In [2]:
def vec_to_mat(vec,n,increasing=False):
    out = []
    if increasing == True:
        for i in arr:
            for t in range(n):
                out.append(i ** (t))
        res = np.mat(out).reshape(len(arr),n)
    else:

        for i in arr:
            for t in range(n):
                out.append(i ** (n-t-1))
        res = np.mat(out).reshape(len(arr),n)
    return res

In [3]:
arr = np.array([1,2,3,4,5])

In [4]:
vec_to_mat(arr,4,increasing=False)

matrix([[  1,   1,   1,   1],
        [  8,   4,   2,   1],
        [ 27,   9,   3,   1],
        [ 64,  16,   4,   1],
        [125,  25,   5,   1]])

In [5]:
vec_to_mat(arr,5,increasing=True)

matrix([[  1,   1,   1,   1,   1],
        [  1,   2,   4,   8,  16],
        [  1,   3,   9,  27,  81],
        [  1,   4,  16,  64, 256],
        [  1,   5,  25, 125, 625]])

## Question 2

In [23]:
def moving_average_sequence(arr, k):
    n = len(arr)
    avg_list = []
    for i in range(n-k+1):
        avg = arr[i:i+k].sum() / k
        avg_list.append(avg)
    return np.array(avg_list)

In [24]:
test_arr = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])

In [25]:
moving_average_sequence(test_arr, 3)

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])